var testJSON = {
    "json": [
        {
            "status": "起飞",
            "preparefromtime": "0705",
            "airplanenumber": "8L9856",
            "departure": "绵阳",
            "destination": "昆明",
            "fnumber": "B6809",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0705",
            "company": "云南祥鹏航空",
            "fromtime": "0707",
            "preparetotime": "0819",
            "plantotime": "0817"
        },
        {
            "status": "起飞",
            "preparefromtime": "0755",
            "airplanenumber": "SC4639",
            "departure": "济南",
            "destination": "绵阳",
            "fnumber": "B7806",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0755",
            "company": "山东航空",
            "fromtime": "0748",
            "preparetotime": "0940",
            "plantotime": "0947"
        },
        {
            "status": "起飞",
            "preparefromtime": "0640",
            "airplanenumber": "G41035",
            "departure": "桂林",
            "destination": "绵阳",
            "fnumber": "B6417",
            "models": "A319",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0640",
            "company": "贵州航空",
            "fromtime": "0652",
            "preparetotime": "0818",
            "plantotime": "0806"
        },
        {
            "status": "正常",
            "preparefromtime": "1440",
            "airplanenumber": "CA1454",
            "departure": "绵阳",
            "destination": "北京",
            "fnumber": "B5329",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1440",
            "company": "中国国际航空",
            "fromtime": "",
            "preparetotime": "1655",
            "plantotime": "1655"
        },
        {
            "status": "起飞",
            "preparefromtime": "0725",
            "airplanenumber": "CA1451",
            "departure": "北京",
            "destination": "绵阳",
            "fnumber": "B7895",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0725",
            "company": "中国国际航空",
            "fromtime": "0739",
            "preparetotime": "1002",
            "plantotime": "0948"
        },
        {
            "status": "起飞",
            "preparefromtime": "",
            "airplanenumber": "CA1452",
            "departure": "绵阳",
            "destination": "北京",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1100",
            "company": "中国国际航空",
            "fromtime": "1105",
            "preparetotime": "1104",
            "plantotime": "1330"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "CA1454",
            "departure": "绵阳",
            "destination": "北京",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1240",
            "company": "中国国际航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1710"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "CA1455",
            "departure": "北京",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1810",
            "company": "中国国际航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2100"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "CA1456",
            "departure": "绵阳",
            "destination": "北京",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2145",
            "company": "中国国际航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "0015"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "GJ8755",
            "departure": "绵阳",
            "destination": "银川",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1645",
            "company": "长龙航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1815"
        },
        {
            "status": "正常",
            "preparefromtime": "1310",
            "airplanenumber": "GJ8755",
            "departure": "杭州",
            "destination": "绵阳",
            "fnumber": "B1675",
            "models": "A320",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1310",
            "company": "长龙航空",
            "fromtime": "",
            "preparetotime": "1529",
            "plantotime": "1529"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "GJ8756",
            "departure": "银川",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1900",
            "company": "长龙航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2040"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "GJ8756",
            "departure": "绵阳",
            "destination": "杭州",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2125",
            "company": "长龙航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2355"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "SC4639",
            "departure": "济南",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0720",
            "company": "山东航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "0955"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "SC4639",
            "departure": "绵阳",
            "destination": "丽江",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1045",
            "company": "山东航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1210"
        },
        {
            "status": "正常",
            "preparefromtime": "1315",
            "airplanenumber": "SC4640",
            "departure": "丽江",
            "destination": "绵阳",
            "fnumber": "B7806",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1315",
            "company": "山东航空",
            "fromtime": "",
            "preparetotime": "1421",
            "plantotime": "1421"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "SC4640",
            "departure": "绵阳",
            "destination": "济南",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1505",
            "company": "山东航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1720"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "SC8441",
            "departure": "太原",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1650",
            "company": "山东航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1850"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "SC8442",
            "departure": "绵阳",
            "destination": "太原",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1935",
            "company": "山东航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2135"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "G41035",
            "departure": "桂林",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0710",
            "company": "贵州航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "0900"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "G41036",
            "departure": "绵阳",
            "destination": "桂林",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2155",
            "company": "贵州航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2340"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "G41040",
            "departure": "南昌",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1245",
            "company": "贵州航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1450"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "G41051",
            "departure": "绵阳",
            "destination": "徐州",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1540",
            "company": "贵州航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1745"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "G41052",
            "departure": "徐州",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1835",
            "company": "贵州航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2040"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "PN6383",
            "departure": "绵阳",
            "destination": "合肥",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2025",
            "company": "西部航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2245"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "PN6384",
            "departure": "合肥",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1705",
            "company": "西部航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1935"
        },
        {
            "status": "正常",
            "preparefromtime": "1100",
            "airplanenumber": "HU7371",
            "departure": "绵阳",
            "destination": "兰州",
            "fnumber": "B7378",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1100",
            "company": "海南航空",
            "fromtime": "",
            "preparetotime": "1158",
            "plantotime": "1158"
        },
        {
            "status": "正常",
            "preparefromtime": "0750",
            "airplanenumber": "HU7371",
            "departure": "海口",
            "destination": "绵阳",
            "fnumber": "B7378",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0750",
            "company": "海南航空",
            "fromtime": "",
            "preparetotime": "0957",
            "plantotime": "0957"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "HU7372",
            "departure": "绵阳",
            "destination": "海口",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1825",
            "company": "海南航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2035"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "HU7372",
            "departure": "兰州",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1615",
            "company": "海南航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1740"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "9C8603",
            "departure": "石家庄",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1605",
            "company": "春秋航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1825"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "9C8604",
            "departure": "绵阳",
            "destination": "石家庄",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1245",
            "company": "春秋航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1505"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "9C8773",
            "departure": "哈尔滨",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0645",
            "company": "春秋航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1105"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "9C8774",
            "departure": "绵阳",
            "destination": "哈尔滨",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1920",
            "company": "春秋航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2300"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "9C8902",
            "departure": "绵阳",
            "destination": "上海浦东",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2020",
            "company": "春秋航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2335"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "9C8907",
            "departure": "宁波",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1605",
            "company": "春秋航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1915"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "9C8908",
            "departure": "绵阳",
            "destination": "宁波",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2020",
            "company": "春秋航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2325"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "3U8533",
            "departure": "绵阳",
            "destination": "南京",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1125",
            "company": "四川航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1335"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "3U8534",
            "departure": "绵阳",
            "destination": "丽江",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1710",
            "company": "四川航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1835"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "3U8583",
            "departure": "郑州",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1125",
            "company": "四川航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1315"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "3U8775",
            "departure": "绵阳",
            "destination": "拉萨",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1220",
            "company": "四川航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1430"
        },
        {
            "status": "起飞",
            "preparefromtime": "",
            "airplanenumber": "3U8775",
            "departure": "杭州",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0900",
            "company": "四川航空",
            "fromtime": "1023",
            "preparetotime": "1022",
            "plantotime": "1135"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "3U8776",
            "departure": "拉萨",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1525",
            "company": "四川航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1740"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "FM9412",
            "departure": "绵阳",
            "destination": "上海浦东",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1225",
            "company": "上海航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1510"
        },
        {
            "status": "起飞",
            "preparefromtime": "0640",
            "airplanenumber": "CZ3399",
            "departure": "广州",
            "destination": "绵阳",
            "fnumber": "B6021",
            "models": "A319",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0640",
            "company": "中国南方航空",
            "fromtime": "0658",
            "preparetotime": "0857",
            "plantotime": "0839"
        },
        {
            "status": "起飞",
            "preparefromtime": "",
            "airplanenumber": "CZ3400",
            "departure": "绵阳",
            "destination": "广州",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1015",
            "company": "中国南方航空",
            "fromtime": "1010",
            "preparetotime": "1009",
            "plantotime": "1245"
        },
        {
            "status": "起飞",
            "preparefromtime": "0705",
            "airplanenumber": "ZH9951",
            "departure": "深圳",
            "destination": "绵阳",
            "fnumber": "B1711",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0705",
            "company": "深圳航空",
            "fromtime": "0727",
            "preparetotime": "0937",
            "plantotime": "0915"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "ZH9953",
            "departure": "深圳",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2000",
            "company": "深圳航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2230"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "ZH9954",
            "departure": "绵阳",
            "destination": "深圳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2315",
            "company": "深圳航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "0055"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "UQ2513",
            "departure": "绵阳",
            "destination": "海口",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1345",
            "company": "乌鲁木齐航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1605"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "UQ2514",
            "departure": "绵阳",
            "destination": "乌鲁木齐",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2125",
            "company": "乌鲁木齐航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "0100"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "UQ2514",
            "departure": "海口",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1740",
            "company": "乌鲁木齐航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2010"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "MF8413",
            "departure": "武汉",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1725",
            "company": "厦门航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1905"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "MF8414",
            "departure": "绵阳",
            "destination": "武汉",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1950",
            "company": "厦门航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2125"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "MF8439",
            "departure": "长沙",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1010",
            "company": "厦门航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1145"
        },
        {
            "status": "正常",
            "preparefromtime": "1235",
            "airplanenumber": "MF8440",
            "departure": "绵阳",
            "destination": "长沙",
            "fnumber": "B5499",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1235",
            "company": "厦门航空",
            "fromtime": "",
            "preparetotime": "1404",
            "plantotime": "1404"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "HO1025",
            "departure": "上海浦东",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1710",
            "company": "上海吉祥航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1950"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "HO1026",
            "departure": "绵阳",
            "destination": "上海浦东",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2140",
            "company": "上海吉祥航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "0000"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "FTU407",
            "departure": "绵阳",
            "destination": "兰州",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0700",
            "company": "民航飞院",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "0820"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "FTU408",
            "departure": "兰州",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0900",
            "company": "民航飞院",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1020"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "FTU457",
            "departure": "绵阳",
            "destination": "桂林",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0801",
            "company": "民航飞院",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "0950"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "FTU458",
            "departure": "桂林",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1030",
            "company": "民航飞院",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1220"
        },
        {
            "status": "起飞",
            "preparefromtime": "",
            "airplanenumber": "NS3283",
            "departure": "西安",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1020",
            "company": "河北航空",
            "fromtime": "1030",
            "preparetotime": "1029",
            "plantotime": "1220"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "NS3284",
            "departure": "绵阳",
            "destination": "西安",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1305",
            "company": "河北航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1425"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "8L9551",
            "departure": "大理",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1225",
            "company": "云南祥鹏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1355"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "8L9552",
            "departure": "绵阳",
            "destination": "大理",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1440",
            "company": "云南祥鹏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1610"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "8L9719",
            "departure": "绵阳",
            "destination": "三亚",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1645",
            "company": "云南祥鹏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1920"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "8L9720",
            "departure": "三亚",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2005",
            "company": "云南祥鹏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2245"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "8L9727",
            "departure": "绵阳",
            "destination": "天津",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1910",
            "company": "云南祥鹏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2125"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "8L9728",
            "departure": "天津",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "2220",
            "company": "云南祥鹏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "0050"
        },
        {
            "status": "起飞",
            "preparefromtime": "0730",
            "airplanenumber": "8L9815",
            "departure": "丽江",
            "destination": "绵阳",
            "fnumber": "B6943",
            "models": "A320",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0730",
            "company": "云南祥鹏航空",
            "fromtime": "0726",
            "preparetotime": "0837",
            "plantotime": "0841"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "8L9816",
            "departure": "绵阳",
            "destination": "丽江",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1530",
            "company": "云南祥鹏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1835"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "8L9855",
            "departure": "昆明",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1555",
            "company": "云南祥鹏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1735"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "8L9856",
            "departure": "绵阳",
            "destination": "昆明",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0740",
            "company": "云南祥鹏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "0915"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "TV9823",
            "departure": "拉萨",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0955",
            "company": "西藏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1205"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "TV9824",
            "departure": "绵阳",
            "destination": "拉萨",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1245",
            "company": "西藏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1500"
        },
        {
            "status": "正常",
            "preparefromtime": "1350",
            "airplanenumber": "TV9887",
            "departure": "拉萨",
            "destination": "绵阳",
            "fnumber": "B6438",
            "models": "A319",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1350",
            "company": "西藏航空",
            "fromtime": "",
            "preparetotime": "1539",
            "plantotime": "1539"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "3U8776",
            "departure": "绵阳",
            "destination": "杭州",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1835",
            "company": "四川航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2105"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "TV9887",
            "departure": "绵阳",
            "destination": "南京",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1650",
            "company": "西藏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1905"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "TV9888",
            "departure": "绵阳",
            "destination": "拉萨",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1255",
            "company": "西藏航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1515"
        },
        {
            "status": "起飞",
            "preparefromtime": "",
            "airplanenumber": "TV9888",
            "departure": "南京",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0955",
            "company": "西藏航空",
            "fromtime": "1015",
            "preparetotime": "1014",
            "plantotime": "1200"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "Y87570",
            "departure": "济南",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1610",
            "company": "扬子江航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1840"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "Y87570",
            "departure": "绵阳",
            "destination": "西昌",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1935",
            "company": "扬子江航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "2100"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "Y87569",
            "departure": "西昌",
            "destination": "绵阳",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0950",
            "company": "扬子江航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1100"
        },
        {
            "status": "正常",
            "preparefromtime": "",
            "airplanenumber": "Y87569",
            "departure": "绵阳",
            "destination": "济南",
            "fnumber": "",
            "models": "",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1210",
            "company": "扬子江航空",
            "fromtime": "",
            "preparetotime": "",
            "plantotime": "1425"
        },
        {
            "status": "起飞",
            "preparefromtime": "0915",
            "airplanenumber": "UQ2513",
            "departure": "乌鲁木齐",
            "destination": "绵阳",
            "fnumber": "B2159",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0915",
            "company": "乌鲁木齐航空",
            "fromtime": "0928",
            "preparetotime": "1240",
            "plantotime": "1227"
        },
        {
            "status": "起飞",
            "preparefromtime": "0830",
            "airplanenumber": "FM9411",
            "departure": "上海浦东",
            "destination": "绵阳",
            "fnumber": "B5703",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "0830",
            "company": "上海航空",
            "fromtime": "0848",
            "preparetotime": "1125",
            "plantotime": "1107"
        },
        {
            "status": "正常",
            "preparefromtime": "1020",
            "airplanenumber": "ZH9952",
            "departure": "绵阳",
            "destination": "深圳",
            "fnumber": "B1711",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1020",
            "company": "深圳航空",
            "fromtime": "",
            "preparetotime": "1231",
            "plantotime": "1231"
        },
        {
            "status": "起飞",
            "preparefromtime": "1025",
            "airplanenumber": "CA1453",
            "departure": "北京",
            "destination": "绵阳",
            "fnumber": "B5329",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1025",
            "company": "中国国际航空",
            "fromtime": "1037",
            "preparetotime": "1259",
            "plantotime": "1247"
        },
        {
            "status": "正常",
            "preparefromtime": "1200",
            "airplanenumber": "8L9816",
            "departure": "兰州",
            "destination": "绵阳",
            "fnumber": "B6943",
            "models": "A320",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1200",
            "company": "云南祥鹏航空",
            "fromtime": "",
            "preparetotime": "1258",
            "plantotime": "1258"
        },
        {
            "status": "正常",
            "preparefromtime": "1300",
            "airplanenumber": "8L9559",
            "departure": "郑州",
            "destination": "绵阳",
            "fnumber": "B1587",
            "models": "B738",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1300",
            "company": "云南祥鹏航空",
            "fromtime": "",
            "preparetotime": "1429",
            "plantotime": "1429"
        },
        {
            "status": "正常",
            "preparefromtime": "1400",
            "airplanenumber": "3U8584",
            "departure": "绵阳",
            "destination": "郑州",
            "fnumber": "B1822",
            "models": "A320",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1400",
            "company": "四川航空",
            "fromtime": "",
            "preparetotime": "1520",
            "plantotime": "1520"
        },
        {
            "status": "正常",
            "preparefromtime": "1425",
            "airplanenumber": "3U8534",
            "departure": "南京",
            "destination": "绵阳",
            "fnumber": "B6406",
            "models": "A319",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1425",
            "company": "四川航空",
            "fromtime": "",
            "preparetotime": "1625",
            "plantotime": "1625"
        },
        {
            "status": "正常",
            "preparefromtime": "1625",
            "airplanenumber": "9C8901",
            "departure": "上海浦东",
            "destination": "绵阳",
            "fnumber": "B1895",
            "models": "A320",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1625",
            "company": "春秋航空",
            "fromtime": "",
            "preparetotime": "1857",
            "plantotime": "1857"
        },
        {
            "status": "正常",
            "preparefromtime": "1530",
            "airplanenumber": "3U8776",
            "departure": "拉萨",
            "destination": "绵阳",
            "fnumber": "B6433",
            "models": "A319",
            "stopposition": "",
            "totime": "",
            "planfromtime": "1530",
            "company": "四川航空",
            "fromtime": "",
            "preparetotime": "1720",
            "plantotime": "1720"
        }
    ]
}